apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: mappings.ambassadorshim.admiralty.io
spec:
  group: ambassadorshim.admiralty.io
  names:
    kind: Mapping
    plural: mappings
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            prefix:
              type: string
            service:
              type: string
          required:
          - prefix
          - service
          type: object
        status:
          properties:
            configured:
              type: boolean
            upToDate:
              type: boolean
          required:
          - configured
          - upToDate
          type: object
      type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
